### ISSUE TITLE
按鈕提示

### ISSUE THREAD

**Issue by cheetosysst** [simba-fs/daniel#8]
讓游標懸浮在按鈕上時顯示功能，例 : 登入 註冊
![圖片](https://user-images.githubusercontent.com/32976729/81659885-bad32500-946c-11ea-9628-dad0b8228aef.png)
不然看太不懂

參考 [https://stackoverflow.com/questions/45456543/make-text-show-up-on-hover-over-button/45456596](https://stackoverflow.com/questions/45456543/make-text-show-up-on-hover-over-button/45456596)

**Comment by simba-fs** [comment]
不錯的提議
https://daniel.simba.nctu.me/help
目前以這個頁面說明

**Comment by simba-fs** [comment]
我寫好了！
現在會提示按鈕的功能
